# Generated by Django 3.2.8 on 2021-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
