# Generated by Django 3.2.8 on 2021-11-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
