# Generated by Django 3.2.8 on 2021-12-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
