# Generated by Django 3.2.8 on 2021-12-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gameinvitation_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='text',
            field=models.TextField(default='Zaprasza cię do swojej rozgrywki'),
        ),
    ]
