# Generated by Django 3.2.8 on 2021-12-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_room_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='main_wallpaper',
        ),
        migrations.AddField(
            model_name='game',
            name='wallpapers',
            field=models.ImageField(blank=True, upload_to='game_wallpapers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='room_key',
            field=models.TextField(default='', max_length=256, unique=True),
        ),
    ]
