# Generated by Django 3.2.8 on 2021-10-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211015_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
