# Generated by Django 3.2.8 on 2021-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='minuses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='pluses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
