# Generated by Django 3.2.8 on 2021-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
