# Generated by Django 3.2.8 on 2021-11-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211116_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preffered_role',
            new_name='preferred_role',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
