# Generated by Django 3.2.8 on 2021-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211117_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1024),
        ),
    ]
