# Generated by Django 3.2.8 on 2022-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='readed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='sended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
