# Generated by Django 3.2.8 on 2021-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('populatity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
